### ISSUE TITLE
Panic on Get

### ISSUE THREAD

**Issue by ashwin95r** [couchbase/moss#14]
I was trying to use moss as a backend store for Dgraph (https://github.com/dgraph-io/dgraph/tree/try/moss). But faced this issue
```
panic: runtime error: slice bounds out of range

goroutine 348 [running]:
github.com/couchbase/moss.(*segment).FindStartKeyInclusivePos(0xc4201ee000, 0xc42a1cb7e0, 0x16, 0x16, 0x16)
	/home/ashwin/go/src/github.com/couchbase/moss/segment.go:313 +0x19b
github.com/couchbase/moss.(*segmentStack).get(0xc4201cac30, 0xc42a1cb7e0, 0x16, 0x16, 0x1e, 0x0, 0x7f7f00, 0xc42006efc0, 0x1f, 0x2a, ...)
	/home/ashwin/go/src/github.com/couchbase/moss/segment_stack.go:90 +0x26b
github.com/couchbase/moss.(*segmentStack).Get(0xc4201cac30, 0xc42a1cb7e0, 0x16, 0x16, 0xc4201cac00, 0x6, 0x6, 0x6, 0x0, 0x6)
	/home/ashwin/go/src/github.com/couchbase/moss/segment_stack.go:74 +0x75
github.com/couchbase/moss.(*Footer).Get(0xc42006efc0, 0xc42a1cb7e0, 0x16, 0x16, 0x465600, 0x1, 0x6, 0xc424e85910, 0x465182, 0xfc7740)
	/home/ashwin/go/src/github.com/couchbase/moss/store_footer.go:426 +0x8a
github.com/couchbase/moss.(*snapshotWrapper).Get(0xc420192fc0, 0xc42a1cb7e0, 0x16, 0x16, 0x0, 0x0, 0xc4200928f0, 0x6, 0x0, 0xc424e85948)
	/home/ashwin/go/src/github.com/couchbase/moss/wrap.go:94 +0x62
github.com/couchbase/moss.(*segmentStack).get(0xc42a1f0d20, 0xc42a1cb7e0, 0x16, 0x16, 0xffffffffffffffff, 0x0, 0xc424e85a00, 0x1, 0x1, 0x6, ...)
	/home/ashwin/go/src/github.com/couchbase/moss/segment_stack.go:110 +0xa2
github.com/couchbase/moss.(*segmentStack).Get(0xc42a1f0d20, 0xc42a1cb7e0, 0x16, 0x16, 0x0, 0x0, 0x414ea2, 0xc42a1f0cd0, 0x50, 0x48)
	/home/ashwin/go/src/github.com/couchbase/moss/segment_stack.go:74 +0x75
github.com/dgraph-io/dgraph/posting.(*List).getPostingList(0xc42a1e9e00, 0x0, 0x0)
	/home/ashwin/go/src/github.com/dgraph-io/dgraph/posting/list.go:190 +0x1ef
github.com/dgraph-io/dgraph/posting.(*List).updateMutationLayer(0xc42a1e9e00, 0xc42a1f0cd0, 0x0)
	/home/ashwin/go/src/github.com/dgraph-io/dgraph/posting/list.go:263 +0x125
github.com/dgraph-io/dgraph/posting.(*List).addMutation(0xc42a1e9e00, 0xfdec00, 0xc425576e40, 0xc42226c660, 0x5, 0x5, 0xb090c8)
	/home/ashwin/go/src/github.com/dgraph-io/dgraph/posting/list.go:340 +0xd7
github.com/dgraph-io/dgraph/posting.(*List).AddMutationWithIndex(0xc42a1e9e00, 0xfdec00, 0xc425576e40, 0xc42226c660, 0x0, 0x0)
	/home/ashwin/go/src/github.com/dgraph-io/dgraph/posting/index.go:171 +0x2da
github.com/dgraph-io/dgraph/worker.runMutations(0x7f62912c2280, 0xc425576e40, 0xc4221e0000, 0x3e8, 0x400, 0x0, 0x0)
	/home/ashwin/go/src/github.com/dgraph-io/dgraph/worker/mutation.go:50 +0x21a
github.com/dgraph-io/dgraph/worker.(*node).processMutation(0xc42008c000, 0x2, 0x114, 0x0, 0xc420f4c000, 0x92c5, 0xa000, 0x0, 0x0, 0x0, ...)
	/home/ashwin/go/src/github.com/dgraph-io/dgraph/worker/draft.go:372 +0x13e
github.com/dgraph-io/dgraph/worker.(*node).process(0xc42008c000, 0x2, 0x114, 0x0, 0xc420f4c000, 0x92c5, 0xa000, 0x0, 0x0, 0x0, ...)
	/home/ashwin/go/src/github.com/dgraph-io/dgraph/worker/draft.go:405 +0x36a
created by github.com/dgraph-io/dgraph/worker.(*node).processApplyCh
	/home/ashwin/go/src/github.com/dgraph-io/dgraph/worker/draft.go:444 +0x49b
```
Any help would be appriciated.
Thanks!

**Comment by steveyen** [comment]
Hi @ashwin95r - thanks for the report.  Would you happen to have a simple way to reproduce?  For example, are there some dygraph tests that I can run that could exercise this?  Thanks

**Comment by steveyen** [comment]
Hi @ashwin95r - by the way, I just took a quick peek at your try-moss branch...  https://github.com/dgraph-io/dgraph/commit/f88ecb04780a2f48b835a75c7a69d81ef4376ae2

I didn't see anything obvious that would explain the panic/crash that you're seeing, but I did see something interesting w.r.t. Snapshots... For moss, the best case of using snapshots is to perform a whole bunch of lookups or iterations on a single snapshot instance -- that is, reuse the snapshot instance a lot.  So, there might be a mismatch w.r.t. your needs vs moss's design.

**Comment by steveyen** [comment]
Oh, found something suspicious...

In the dgraph/lists.go batchSync() code, it appears to be reusing the batch in the for loop...

https://github.com/dgraph-io/dgraph/blob/try/moss/posting/lists.go#L467

Instead, after calling ExecuteBatch(), please create a brand new batch instead of reusing the old instance, and hopefully that fixes the issue.

**Comment by ashwin95r** [comment]
Hi @steveyen - Thank you very much for the help. Creating a new batch did help fix the issue. (Though just wondering if reusing it by mistake should return an error?)

Also, is snapshot the only way to read the data from moss? If so, is it not suited for concurrent writes  and reads (on those latest writes)?

**Comment by steveyen** [comment]
Hi @ashwin95r - cool, going to mark this issue as closed then.

> Though just wondering if reusing it by mistake should return an error?

Interesting question.  I'm usually a bit wary of adding extra code in the "hot paths" of data ingest... where the implementation that pops to mind would have a cost that every batch.Set/Delete() would need to check whether its batch had already been executed and/or closed.

And, although the current behavior is documented (https://godoc.org/github.com/couchbase/moss#Collection ExecuteBatch()), I guess it's not documented very prominently.  So, just added that idea in https://github.com/couchbase/moss/issues/16

> Also, is snapshot the only way to read the data from moss?  If so, is it not suited for concurrent writes and reads (on those latest writes) as the older snapshots wouldn't have these writes?

Yes, creating a snapshot the only way to read from moss right now.  We have apps that perform concurrent reads and writes into moss right now, and depend on the snapshot semantics in order to have a stable view (never see "half a batch" and also never see mutations that "happened later"), even if the reader is performing tons of iterations and Get()'s on its snapshot.

But, I think you're the second person that I've heard ask about a non-snapshot Get() API, so a mini-crowd is perhaps starting to form for that kind of feature, I guess :-)  Tracking that in a new issue: https://github.com/couchbase/moss/issues/15

Finally, thanks for the feedback!
